id: P5FFC2AC1
initial_creation_type: input
source_metadata:
  title: Shechen Kongtrul Series
  language: bo
  description: 'Texts by and about Pema Drimé Lekpé Lodrö (zhe chen kong sprul padma
    dri med legs pa''i blo gros, 1901-c.1960), the immediate reincarnation of Jamgön
    Kongtrul Lodrö Thaye at Shechen Monastery:'
  volume:
    04f67b208a0541aebae5731fb8437d74:
      title: Prayer to Shechen Kongtrul as Vajrasattva
      parent: Prayers
created_at: '2022-03-01T01:35:04.352408'
last_modified_at: '2022-03-01T01:35:04.352411'
statistics:
  total_words: 143
  total_non_words: 27
quality:
  non_words_ratio: 0.19
